### ISSUE TITLE
Cannot run because of README errors

### ISSUE THREAD

**Issue by djjonbrown** [DanWilkerson/acre-api#2]
- change the require to ('acre-api')
- acreApi.street example does not work
- acreApi.search works if changing the call to 
  `acreApi.search(1000, 'Liberty', function(err, parcel) {
  ...
  });`

**Comment by DanWilkerson** [comment]
Thank you! README should be updated with correct examples.

**Comment by mogley25** [comment]
Hi, I'm not sure how to run this, but when I did by double clicking the index.js file. I get an error saying "__dirname is not defined"
Plz help. Thx.
